export const SOCKET_EVENTS = {
  SEND_MESSAGE: 'message:send',
  NEW_MESSAGE: 'message:new',
  MESSAGE_DELIVERED: 'message:delivered',
  MESSAGE_READ: 'message:read',
  MESSAGE_EDITED: 'message:edited',
  MESSAGE_DELETED: 'message:deleted',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  TYPING_STARTED: 'typing:started',
  TYPING_STOPPED: 'typing:stopped',
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  JOIN_ROOMS: 'join:rooms',
  JOIN_ROOM: 'room:join',
  LEAVE_ROOM: 'room:leave',
  MESSAGE_REACTION: 'message:reaction',
  REACTION_UPDATED: 'reaction:updated',
  GROUP_UPDATED: 'group:updated',
  MEMBER_ADDED: 'member:added',
  MEMBER_REMOVED: 'member:removed',
  ERROR: 'error',
};
